# Generated by Django 4.2 on 2023-04-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('device_ip', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SNMPInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid_name', models.CharField(max_length=255)),
                ('oid', models.CharField(max_length=255)),
                ('returnValue', models.CharField(max_length=255)),
            ],
        ),
    ]
